export const screenshots = [
  {
    name: "light email with contact details",
    file: "email-light.png",
    text: [
      "Your review is ready",
      "Alex Morgan",
      "alex@example.com",
      "Please review the notes before Friday.",
      "+31 6 12345678",
      "Keep this message private.",
    ],
  },
  {
    name: "dark chat with small labels",
    file: "chat-dark.png",
    text: [
      "Project chat",
      "Alex Morgan",
      "The review is ready.",
      "alex@example.com",
      "Sam Taylor",
      "Thanks, I will check the document today.",
    ],
  },
  {
    name: "small contact card with an invoice identifier",
    file: "contact-small.png",
    text: [
      "Contact details",
      "Alex Morgan",
      "alex@example.com",
      "+31 6 12345678",
      "INV-2026-1042",
      "Review these details before sharing.",
    ],
  },
  {
    name: "dense document paragraphs and section headings",
    file: "document-paragraphs.png",
    text: [
      "What is a medical document?",
      "Medical documents are legal documents.",
      "differentiate between clinical and non-clinical documentation.",
      "patient information leaflet",
      "Discharge Summary",
      "Mental Status Examination",
      "Operative Report",
      "be as clear and concise as possible.",
    ],
  },
  {
    name: "record table with dates, identifiers, and text in its last row",
    file: "record-table.png",
    text: [
      "Medical Record Summary",
      "Susan",
      "Hall",
      "03/14/1971",
      "ABC123",
      "Liza King (RN)",
      "02/18/2021",
      "was scanned, and tattooed",
    ],
  },
  {
    name: "form labels across columns, checkboxes, and ruled fields",
    file: "patient-form.png",
    text: [
      "Patient Information Form",
      "When did your problem start?",
      "Past Medical History",
      "Breathing Problems",
      "Kidney Problems",
      "Depression",
      "Surgeries/Hospitalizations",
      "Reason for Medication",
      "No Known allergies",
      "Signature",
    ],
  },
  {
    name: "handwritten article notes",
    file: "handwritten-notes.png",
    text: [
      "Only a matter of style?",
      "For educational purposes",
      "American Mathematical",
      "February 1995",
      "We have added line numbers",
      "In line 77",
    ],
  },
  {
    name: "handwriting inside a PDF editor screenshot",
    file: "handwritten-editor.png",
    text: [
      "This is an OCR",
      "(optical character recognition)",
      "test for TechTerms.com.",
      "The following text was recognized by OCR:",
    ],
  },
  {
    name: "small labels and fields in a desktop application",
    file: "desktop-record.png",
    text: [
      "Handy patients enterprise edition",
      "Digestive",
      "Thursday, 22 Jan 2009",
      "Anderson",
      "David",
      "Normal abdomen noises",
      "Little pain on the right lower area",
      "Father ask many questions, add 10 minutes to consultation",
    ],
  },
  {
    name: "GNU Health fields, condition codes, and dates",
    file: "gnu-health.png",
    text: [
      "Ana Betz",
      "allergy to penicillin",
      "Type 1 diabetes mellitus",
      "Severe allergic reactions to β-lactams.",
      "938291",
      "01/07/1991",
      "11/10/1993",
      "10/04/1985",
      "GNU777ORG777",
    ],
  },
  {
    name: "EHR panels with names, dates, medication, and small footer text",
    file: "accumed-record.png",
    text: [
      "Matulich,Kylie",
      "01/17/2003",
      "Diastolic is 90+, monitor for High BP.",
      "Depressive disorder, not elsewhere classified",
      "Ventolin HFA",
      "Proventil HFA",
      "03/29/2017",
      "12.10.419.68",
    ],
  },
  {
    name: "small repair invoice with identifiers, amounts, and payment terms",
    file: "repair-invoice.png",
    text: [
      "Electronics Repair Invoice",
      "#ERP-2053-001",
      "October 31, 2053",
      "Efrain Abshire",
      "efrain@you.mail",
      "Software Troubleshooting",
      "$110.00",
      "Please make the payment by November 14, 2053.",
    ],
  },
  {
    name: "small electronic invoice with dates, address, and currency amounts",
    file: "electronic-invoice.png",
    text: [
      "Company name",
      "Electronic invoice",
      "Aden Matchett",
      "Vandelay Group",
      "123 Main Street",
      "06/03/2019",
      "07/03/2019",
      "$5,500.00",
      "$500.00",
      "Amount Due (CAD)",
    ],
  },
];
